Repository FB-CodeQuest/my-room, pull requests merged in 2025-01, with the labels that each got.

#4 1 feat/login page
  frontend/src/App.js
  frontend/src/assets/images/icon-google.svg
  frontend/src/assets/images/icon-kakao.png
  frontend/src/assets/images/icon-naver.png
  frontend/src/components/Button/Button.jsx
  frontend/src/components/Button/Button.scss
  frontend/src/components/CheckBox/CheckBox.jsx
  frontend/src/components/CheckBox/CheckBox.scss
  frontend/src/components/DropDown.jsx
  frontend/src/components/Form.jsx
  frontend/src/components/Input/Input.jsx
  frontend/src/components/Input/Input.scss
  frontend/src/components/LinkButton.jsx
  frontend/src/components/RadioButton.jsx
  frontend/src/components/ToggleButton/ToggleButton.jsx
  frontend/src/components/ToggleButton/ToggleButton.scss
  frontend/src/index.js
  frontend/src/pages/Login/LoginPage.jsx
  frontend/src/pages/Login/LoginPage.scss
  frontend/src/styles/global.scss
  frontend/src/styles/variables.scss
Labels: ✨ Feat, FE

#6 2 feat/user rest api
  backend/build.gradle
  backend/gradlew
  backend/gradlew.bat
  backend/src/main/java/com/fbcq/be/BackendApplication.java
  backend/src/main/java/com/fbcq/be/controller/UserController.java
  backend/src/main/java/com/fbcq/be/domain/User.java
  backend/src/main/java/com/fbcq/be/dto/request/LoginRequest.java
  backend/src/main/java/com/fbcq/be/dto/request/SignUpRequest.java
  backend/src/main/java/com/fbcq/be/dto/response/LoginResponse.java
  backend/src/main/java/com/fbcq/be/mapper/UserMapper.java
  backend/src/main/java/com/fbcq/be/service/UserService.java
  backend/src/main/java/com/fbcq/be/service/UserServiceImpl.java
  backend/src/main/resources/application.properties
  backend/src/main/resources/mapper/UserMapper.xml
  backend/src/test/java/com/fbcq/be/BackendApplicationTests.java
Labels: ✨ Feat, BE

#7 3 feat/email rest api
  backend/build.gradle
  backend/gradlew
  backend/gradlew.bat
  backend/src/main/java/com/fbcq/be/BackendApplication.java
  backend/src/main/java/com/fbcq/be/controller/EmailController.java
  backend/src/main/java/com/fbcq/be/controller/UserController.java
  backend/src/main/java/com/fbcq/be/dto/request/EmailRequest.java
  backend/src/main/java/com/fbcq/be/dto/response/EmailResponse.java
  backend/src/main/java/com/fbcq/be/mapper/UserMapper.java
  backend/src/main/java/com/fbcq/be/service/EmailService.java
  backend/src/main/java/com/fbcq/be/service/EmailServiceImpl.java
  backend/src/main/java/com/fbcq/be/service/UserService.java
  backend/src/main/java/com/fbcq/be/service/UserServiceImpl.java
  backend/src/main/resources/application.properties
  backend/src/main/resources/mapper/UserMapper.xml
Labels: ✨ Feat, BE

#13 CORS 처리, checkEmail, JWT 추가 반영
  backend/build.gradle
  backend/src/main/java/com/fbcq/be/BackendApplication.java
  backend/src/main/java/com/fbcq/be/config/SecurityConfig.java
  backend/src/main/java/com/fbcq/be/config/SwaggerConfig.java
  backend/src/main/java/com/fbcq/be/config/WebConfig.java
  backend/src/main/java/com/fbcq/be/controller/EmailController.java
  backend/src/main/java/com/fbcq/be/controller/UserController.java
  backend/src/main/java/com/fbcq/be/domain/User.java
  backend/src/main/java/com/fbcq/be/dto/request/EmailVerifyRequest.java
  backend/src/main/java/com/fbcq/be/dto/request/ResetPasswordRequest.java
  backend/src/main/java/com/fbcq/be/dto/request/SignUpRequest.java
  backend/src/main/java/com/fbcq/be/dto/response/LoginResponse.java
  backend/src/main/java/com/fbcq/be/jwt/JwtAuthenticationFilter.java
  backend/src/main/java/com/fbcq/be/jwt/JwtUtil.java
  backend/src/main/java/com/fbcq/be/mapper/UserMapper.java
  backend/src/main/java/com/fbcq/be/service/EmailService.java
  backend/src/main/java/com/fbcq/be/service/EmailServiceImpl.java
  backend/src/main/java/com/fbcq/be/service/UserService.java
  backend/src/main/java/com/fbcq/be/service/UserServiceImpl.java
  backend/src/main/resources/application.properties
  backend/src/main/resources/mapper/UserMapper.xml
Labels: BE, FE, chore
